### ISSUE TITLE
印刷所の情報を調べておく

### ISSUE THREAD

**Issue by tabunmuri** [mokumoku-onsen/onsen-document#3]
- [ ] 価格
- [ ] 印刷方式
- [ ] 最終納期

**Comment by kansai-inoshita** [comment]
参考例です。
http://www.doujin-adp.sakura.ne.jp/index.html
<br>
価格

- 表紙カラー・本文モノクロ
50部　¥13,800‐

<br>
印刷方式

- オンデマンド

<br>
最終納期

- 8月7日（月）AM9：30
